### ISSUE TITLE
项目名

### ISSUE THREAD

**Issue by Menci** [CodeIntro-CN/early-suggestion#10]
我认为本项目并不仅仅局限于“代码”，所以“code”放在名字里可能并不合适。

另外，我认为“intro”的其他候选词有“tutorial”。

**Comment by Menci** [comment]
提议一个项目名：Hello, world!
（

**Comment by Ilgharkus** [comment]
感觉本项目的作用像是为国内计算机教育填坑（或者搭把梯子让同学们爬上来）的作用
所以或许项目名称可以与梯子（或者其他相似象征意义的事物）有关？

或者也可以秉承开源项目喜爱用动物做名称的精神，用个有相似象征意义的、可爱的动物。

**Comment by ayaka14732** [comment]
我觉得可以叫 _What I Wish I Knew Before Majoring in CS_

**Comment by HeartyYF** [comment]
_Things Before Code_

**Comment by Maoyao233** [comment]
支持“Hello, world!”

**Comment by BillXWB** [comment]
支持“Hello, world!”.
“What I Wish I Knew Before Majoring in CS”挺好但是太长了，或许可以当副标题之类的？

**Comment by comradez** [comment]
我更支持 _Things Before Code_ 
感觉Hello World作为一个Organization的名字并不合适，它太大、太知名了。 _Hello-World-CN_ 或许可以？

**Comment by ayaka14732** [comment]
其实应该是 _Things Before Coding_？

_Things Before Code_ 是「有代码之前的东西」（比如算盘、电子管什么的 XD）

_Things Before Coding_ 才是「写代码之前的东西」

**Comment by Ilgharkus** [comment]
支持 Things Before Coding

**Comment by LaoshuBaby** [comment]
支持 Things Before Coding

**Comment by comradez** [comment]
支持 _Things Before Coding_ 的人更多一点，那么项目名就这样定了。
