### ISSUE TITLE
[ 内容 ] 内容呈现给读者的形式 ...？

### ISSUE THREAD

**Issue by kernelbin** [CodeIntro-CN/early-suggestion#11]
**内容呈现形式**

似乎最早在proposal里提到想法是在线书籍
而 missing-semi 的呈现形式是以视频和讲义的形式呈现的知识

不过群友似乎也提出了以 oi-wiki 的形式或者是 百科全书 的形式

因此开此 issue 用于讨论

**Comment by kenlig** [comment]
或者做个网站也可以？我感觉没必要局限在PDF里吧

**Comment by comradez** [comment]
我的建议是md写作、mkdocs生成、github pages和gitee pages托管。
用gitee pages的想法主要是一来方便国内访问，二来这是免费服务，可以规避未来可能产生的麻烦。
mkdocs有pdf渲染的插件，网站和pdf不冲突。

**Comment by Ilgharkus** [comment]
个人鄙见，如果精力足够的话维护一套类似教程+Wiki的库是最好的，因为大部分计算机专业的新生还没有养成阅读Wiki的习惯和能力。
以实际情况来看，前期的精力放到编写教程（或讲义）形式的文档是最好的，后期再进行Wiki形式相关分支的内容补充。

**Comment by Ilgharkus** [comment]
> 我的建议是md写作、mkdocs生成、github pages和gitee pages托管。
> 用gitee pages的想法主要是一来方便国内访问，二来这是免费服务，可以规避未来可能产生的麻烦。
> mkdocs有pdf渲染的插件，网站和pdf不冲突。

十分同意。
这套工具链现在已经很成熟了，成员编写不会有OS平台方面的限制，而且Github Pages和Gitee Pages同时保证了有能力和没能力珂学上网的同学们均有稳定的成熟的访问途径，社区成员也不会产生网站部署与维护的一些精力或经济方面的压力。

同时在不伤害社区成员的工作成果的前提下，秉着知识共享的精神，我认为在页面上提供Markdown源文件和PDF文件的下载链接是有必要的。

**Comment by Ilgharkus** [comment]
个人感觉，编译成 HTML Page 可以用mkdocs，如果要编译成PDF格式还是推荐使用 Pandoc , LaTeX 排版还是很好看的，虽然不像Markdown那样适合手写。

**Comment by FLDPMpang** [comment]
用vuepress吧,感觉入门不太需要使用latex,后期单独建一个wiki站

**Comment by LaoshuBaby** [comment]
感觉没必要以wiki的形式？还是单篇文档方便？

**Comment by LaoshuBaby** [comment]
latex的话感觉有点舍本逐末了呢
markdown写起来方便顺手，改也好改

如果真的以后有集结成册印刷的情况再考虑latex吧
目前我们还是要追求互联网电子书的“效率和实时性”，“易修改性”这些

**Comment by panda2134** [comment]
VuePress也可以考虑，交互性强的地方可以手写component，更方便一些

**Comment by opsiff** [comment]
我觉得内容可能非常繁多，以多种方式分布，可能需要针对不同的需要提供不同的索引编排方式，内容多是重要的，而索引灵活也是重要的。

**Comment by opsiff** [comment]
也就是说可以针对已有的内容提供多种不同的展现方式。

**Comment by Menci** [comment]
PDF 有个问题就是不太方便阅读，而且排版也会很别扭，图片在翻页附近的话，可能会被切开（或者空出来一块）

我提议用类似 gitbook 的形式提供，左边目录右边内容，按照学习顺序排列

**Comment by FLDPMpang** [comment]
我的理想是[这种模式](https://gitee.com/opensource-guide/) ,同时部署在github和gitee上

**Comment by comradez** [comment]
这条回复同时适用于#7 和#11

4.23的截止日期已经过去了，我简单地整理一下大家的意见：

markdown书籍的呼声比较高，类似https://gitee.com/opensource-guide 和 https://101.lug.ustc.edu.cn/ 的线性目录在线书籍，用markdown撰写并部署在网站上。目前来看，支持这一方案的人数最多，因此目前可以先按照这一方案进行。

@panda2134和@FLDPMpang提到的VuePress在交互性上比起markdown静态网站有明显优势，在后续遇到类似需求时可以考虑。

写wiki的呼声并不很高，暂且可以搁置，后续如果社区有精力再做也不迟。
