### ISSUE TITLE
[ 许可证 ] 项目应该使用怎样的许可证？

### ISSUE THREAD

**Issue by Ilgharkus** [CodeIntro-CN/early-suggestion#15]
虽然现在就开始讨论许可证的问题有点早，但是不可否认这也是十分重要的一件事。

项目应该使用怎样的许可证？
CC-BY-SA 4.0 ?
GNU FDL ?
......?

**Comment by HeartyYF** [comment]
个人意见是，成员将所写部分“捐”给项目，项目统一以某种许可证形式开源，并以某种形式注明贡献

**Comment by ayaka14732** [comment]
CC BY-SA 4.0 是比较通行的做法吧

**Comment by comradez** [comment]
我提议CC BY-SA 4.0
（其实一开始打算copyleft，但是在国内似乎这样做是羊入虎口……

**Comment by LaoshuBaby** [comment]
提议CC BY-NC-SA？

因为难以保证一些国内无良自媒体直接大段落的抄袭引用，还加以断章取义之类的，内容质量没有保障，还打着这个名号的话就很麻烦了。（而且那也更不可能实时更新的）

带上NC的话，起码如果真的有机会去投诉告状之类，能增加一些胜算的吧（？我不是很懂，各位有法律熟悉的可以帮忙补充（但是我对商业化和国内互联网环境真的厌烦到顶））

**Comment by LaoshuBaby** [comment]
> 
> 
> 我提议CC BY-SA 4.0
> （其实一开始打算copyleft，但是在国内似乎这样做是羊入虎口……

（甚至GFDL也不是不可以？（极端主义者如是说

**Comment by ayaka14732** [comment]
许可证没有必要那么极端吧？如果有人转载，附上原链接的话读者自然可以找过来。至于法律纠纷…从目前来看我们这个项目的维护者好像没有精力处理这些。

**Comment by LaoshuBaby** [comment]
法律纠纷确实，防不了小人的，但是为甚么不预留一部分属于自己的权力呢？


此外，指望中国的自媒体转载留链接，算了吧，和指望小偷进家门轻声轻脚一样可笑





------------------&nbsp;Original&nbsp;------------------
From: "Ayaka ***@***.***&gt;; 
Date: 2021年4月26日(星期一) 下午3:42
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [CodeIntro-CN/early-suggestion] [ 许可证 ] 项目应该使用怎样的许可证？ (#15)





 
许可证没有必要那么极端吧？如果有人转载，附上原链接的话读者自然可以找过来。至于法律纠纷…从目前来看我们这个项目的维护者好像没有精力处理这些。

**Comment by comradez** [comment]
有效意见不是很多，还是按照多数原则暂定CC  BY-SA 4.0。
