### ISSUE TITLE
[ 内容 ] 编程业界黑话

### ISSUE THREAD

**Issue by kernelbin** [CodeIntro-CN/early-suggestion#27]
在编程/开源社区聊天的时候经常能看到各种黑话，诸如：
- LGTM
- AKA
- CC
- PR
- ACK
- NACK
- WIP
初次见到这些单词可能完全不知道什么意思，可以专门整理并收集。

*当然，肯定这类工作已经早有人做过，我只是觉得这也是初学者所需要的知识，该项目应一并收集这些黑话*

**Comment by LaoshuBaby** [comment]
+ 关于互联网聊天中的缩写大全：https://github.com/itorr/nbnhhsh      （不一定和计算机沾边）
+ 计算机的缩写：
    + https://github.com/jihch/short-name
    + https://github.com/jihch/abbreviation
    （建议直接收了这里面的）

**Comment by kernelbin** [comment]
> * 关于互联网聊天中的缩写大全：https://github.com/itorr/nbnhhsh      （不一定和计算机沾边）
> * 计算机的缩写：
>   
>   * https://github.com/jihch/short-name
>   * https://github.com/jihch/abbreviation
>     （建议直接收了这里面的）

上面这几个repo收集的黑话都不是很全，连我上面列出来的都没覆盖全...可以再找找别的repo

**Comment by LaoshuBaby** [comment]
好耶，快点一起来建仓库吧




------------------&nbsp;Original&nbsp;------------------
From: "He ***@***.***&gt;; 
Date: 2021年4月23日(星期五) 下午3:50
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [CodeIntro-CN/early-suggestion] [ 内容 ] 编程业界黑话 (#27)





   
 
关于互联网聊天中的缩写大全：https://github.com/itorr/nbnhhsh      （不一定和计算机沾边）
 
 
 
计算机的缩写：
  
https://github.com/jihch/short-name
 
https://github.com/jihch/abbreviation
 （建议直接收了这里面的）
  
   
上面这几个repo收集的黑话都不是很全，连我上面列出来的都没覆盖全...可以再找找别的repo

**Comment by xiong35** [comment]
我认为这种级别(指知识的深度&难度&指代的明确程度)的黑话并不需要在这个仓库中科普

1. 这种专有名词在百上一搜就能搜到诸多解答(因为指代明确)
2. 小白接触这些专有名词的机会不多(因为水平有限)
3. 初学者不需要这么快接触这些概念, 如 ACID 原则, 没有一定代码经验, 看到解释的时候很难能理解为什么要这么做
4. 上述仓库中的解释只有短短一句话, 还是在用术语解释术语, 并不能让萌新理解这是什么, 反而会让他更蒙圈

综上, 我认为只需要介绍简单而必要的概念, 如 编译, 命令行 等, 而非诸多的缩写

**Comment by kernelbin** [comment]
make sense. 将关闭该 issue

**Comment by HeartyYF** [comment]
可以考虑把这部分放进附录里之类
