### ISSUE TITLE
该如何部署本项目的内容？

### ISSUE THREAD

**Issue by HeartyYF** [CodeIntro-CN/early-suggestion#7]
以何种形式编写？markdown 还是别的什么？latex？
如何呈现给读者？在线阅读？实时渲染？可下载文本？
如果在线阅读的话，挂在哪？需要保证不科学上网也能看吗？
下载的话，从哪里分发？
请各位给出建议，感谢。

**Comment by Hecate2** [comment]
markdown
github为中心，gitee上复制一份，国内博客平台适当宣传留链接

**Comment by LaoshuBaby** [comment]
顺便定期生成PDF供传阅，以release的形式
（但是一定在里面写明最新的需要去gh、gitee
（不然容易成为学长的祖传PDF（笑

**Comment by Ilgharkus** [comment]
我个人十分青睐的方式是使用Markdown编写，并使用一个统一的生成器生成PDF文档，网站使用Github Pages做部署，同时在 Gitee 与 Gitee Pages 维护一份镜像供没有珂学上网能力的同学可以稳定地访问，同时在页面上提供 md 源文件和 PDF文档的下载链接。

> 顺便定期生成PDF供传阅，以release的形式
> （但是一定在里面写明最新的需要去gh、gitee
> （不然容易成为学长的祖传PDF（笑

当然这种机制也是十分好的，以release的方式定期打包统一发布，方便同学们下载。
在文档内部标明永久更新链接以及项目链接也是很有必要的。

**Comment by Blizzard37** [comment]
投markdown一票 然后尽量做到定时更新嘛 之后传播的话感觉大家都可以挂在自己的站点上 总之多多分享 多多传播总是好的

**Comment by LaoshuBaby** [comment]
> 
> 
> 投markdown一票 然后尽量做到定时更新嘛 之后传播的话感觉大家都可以挂在自己的站点上 总之多多分享 多多传播总是好的

传播的话，可以类似微软文档那样，实时爬取和更新，只有一个源那就是这个仓库，这样子？

可以避免后期乱掉吧

**Comment by panda2134** [comment]
markdown比较方便，之后用文档生成工具弄成网页就行，投markdown一票

**Comment by comradez** [comment]
这条回复同时适用于#7 和#11

4.23的截止日期已经过去了，我简单地整理一下大家的意见：

markdown书籍的呼声比较高，类似https://gitee.com/opensource-guide 和 https://101.lug.ustc.edu.cn/ 的线性目录在线书籍，用markdown撰写并部署在网站上。目前来看，支持这一方案的人数最多，因此目前可以先按照这一方案进行。

@panda2134和@FLDPMpang提到的VuePress在交互性上比起markdown静态网站有明显优势，在后续遇到类似需求时可以考虑。

写wiki的呼声并不很高，暂且可以搁置，后续如果社区有精力再做也不迟。
